name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ["1.13.x"]
        otp: ["24.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Create tmp dir
        run: mkdir tmp
      - name: Run Tests
        run: mix test

  dialyzer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ["1.13.x"]
        otp: ["24.x"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        with:
          path: _build
          key: build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Create plts dir
        run: mkdir -p priv/plts
      - uses: actions/cache@v2
        with:
          path: priv/plts
          key: plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Run mix dialyzer
        run: mix dialyzer
